feat: IDKit v1 migration guide
worldcoin/world-id-docs pull request #244
Opened 2023-12-06 22:35 UTC by 0xPenryn

adds a migration guide and updates the announcement banner on the homepage.

several links may appear broken until other PR's are merged into idkit-v1-updates.

TODO: include links to blog posts once available.

2023-12-07 13:01 UTC, pdtfh requested changes

2023-12-08 09:51 UTC, pdtfh commented on src/pages/reference/world-id-2-migration-guide.mdx
> +
We should start with the overall changes of World ID 2.0 & then talk about breaking changes in IDKit

2023-12-08 09:52 UTC, pdtfh commented on src/pages/reference/world-id-2-migration-guide.mdx
> +### Email Sign In for Developer Portal
```suggestion
### Use your email to sign in to the Developer Portal
```
or something along those lines. after coming back the title is confusing

2023-12-08 22:48 UTC, 0xPenryn commented on src/pages/reference/v1-migration-guide.mdx
> +### Wallet Bridge
highlighted protocol internals as first reference and updated name

2023-12-08 23:08 UTC, 0xPenryn commented on src/pages/reference/v1-migration-guide.mdx
> +The `SignInWithWorldID` and `SignInButton` components have been removed from IDKit. All applications that wish to use Sign In with Worldcoin should do so through our [OIDC Provider](/id/sign-in).
created a linear issue for this, deprioritizing for now

2023-12-09 14:24 UTC, pdtfh commented on src/components/Navigation.tsx
> +			{ title: 'World ID Lite', href: '/further-reading/world-id-lite' },
let's keep it under the main World ID section, at least for a few months

2023-12-09 14:25 UTC, pdtfh commented on src/pages/index.mdx
> +		<span className="block text-lg font-bold">World ID 2.0 is live!</span>
```suggestion
		<span className="block text-lg font-bold">Announcing World ID 2.0!</span>
```

2023-12-09 14:28 UTC, pdtfh commented on src/pages/further-reading/world-id-lite.mdx
> +## Benefits
We need to add a section above this, with suggestions on when to use World ID Lite and the trade-offs versus using the Orb.

2023-12-09 14:29 UTC, pdtfh commented on src/pages/further-reading/world-id-lite.mdx
> +- **Credential Strength:** World ID Lite is a stronger credential than the previous `phone` credential. It is more difficult and more expensive for an adversary to obtain a new unique device than a n
```suggestion
```

2023-12-09 14:29 UTC, pdtfh approved these changes
merging to avoid conflicts, let's address outstanding comments in a separate PR

2023-12-09 14:30 UTC, merged